name: on-push
on: [ push ]
jobs:
  check-pre-commit:
    runs-on: ubuntu-latest
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install libgpgme-dev
      - uses: actions/checkout@v3
      - uses: actions/setup-python@v4
        with:
          python-version: 3.x
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: stable
          components: clippy
      - run: python -m pip install pre-commit
      - uses: actions/cache@v3
        with:
          path: ~/.cache/pre-commit
          key: pre-commit|${{ env.pythonLocation }}|${{ hashFiles('.pre-commit-config.yaml') }}
      - run: pre-commit run --show-diff-on-failure --color=always --all-files

  run-tests:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        rust-version: [stable, beta, nightly]
    steps:
      - run: |
          sudo apt-get update
          sudo apt-get install gpg libgpgme-dev
      - run: |
          gpg --import tests/8497251104B6F45F.key
          echo -e "trust\n5\ny" | gpg --command-fd 0 --edit-key 8497251104B6F45F
      - uses: actions/checkout@v3
      - uses: ATiltedTree/setup-rust@v1
        with:
          rust-version: ${{ matrix.rust-version }}
      - run: cargo test --no-fail-fast
